version: 2.1
jobs:
    build:
        docker:
            - image: gailyganesh/trial:latest
            - auth:
                username: "gailyganesh"
                password: $DOCKER_HUB_PSWD
        steps:
            - checkout
            - run: echo "Hello world"
