version: 2.1
jobs:
    build:
        docker:
            - image: gailyganesh/trial:latest
        steps:
            - checkout
            - run: 
                name: Code Has Arrived
                command: |
                    ls -al
                    echo "That is ur code"
            - run:
                name: check tools directory exist
                command: |
                    cd
                    ls -a
            - run:
                name: clean the project
                command: |
                    cd ~/project
                    ./run.sh clean
            - run:
                name: generate the project
                command: |
                    cd ~/project
                    ./run.sh generate
            - run:
                name: build the project
                command: |
                    cd ~/project
                    ./run.sh build