version: 2
jobs:
    build:
        docker:
            - image: https://hub.docker.com/repository/docker/gailyganesh/trial:latest
            - auth:
                username: "gailyganesh"
                password: $DOCKER_HUB_PSWD
        steps:
            - checkout
            - shell: /bin/sh
            - command: |
                echo Hello world