version: 2.1
jobs:
    build:
        docker:
            - image: gailyganesh/trial:latest
        steps:
            - checkout
            - run: 
                name: Code Has Arrived
                command: |
                    ls -al
                    echo "That is ur code"
            - run:
                name: PWD
                command: |
                    pwd
                    echo "Current direc" pwd 