version: 2
jobs:
    build:
        docker:
          - image: "gailyganesh/trial:tagname"
          - auth:
                username: "gailyganesh"
                password: $DOCKER_HUB_PSWD
        steps:
            - checkout
            - run: echo "Hello world"